In [6]:
import pandas as pd

In [7]:
a = {
    "Name":["Arham","Ameen","Ammar"],
    "profession" : ["development" , "designer" , "marketing"],
    "city" : ["hyd","karachi","Lahore"]

}
print(a)

{'Name': ['Arham', 'Ameen', 'Ammar'], 'profession': ['development', 'designer', 'marketing'], 'city': ['hyd', 'karachi', 'Lahore']}

In [8]:
b = pd.DataFrame(a)

In [9]:
b

    Name   profession     city
0  Arham  development      hyd
1  Ameen     designer  karachi
2  Ammar    marketing   Lahore

In [10]:
b["gender"] = ["male","male","male"]

In [11]:
b

    Name   profession     city gender
0  Arham  development      hyd   male
1  Ameen     designer  karachi   male
2  Ammar    marketing   Lahore   male

In [12]:
b["Age"] = [33,32,32]

In [13]:
b

    Name   profession     city gender  Age
0  Arham  development      hyd   male   33
1  Ameen     designer  karachi   male   32
2  Ammar    marketing   Lahore   male   32

In [14]:
b[b["Age"]>20]

    Name   profession     city gender  Age
0  Arham  development      hyd   male   33
1  Ameen     designer  karachi   male   32
2  Ammar    marketing   Lahore   male   32

In [15]:
st = {
    "Name":["Arham","Ameen","Ammar","Khan","Ali"],
    "Obtain" : [80 , 23 , 32,60,26],
    "Total_Marks" : [100,100,100,100,100]

}

In [21]:
df = pd.DataFrame(st)

In [22]:
df["Percentage"] = (df["Obtain"] / df["Total_Marks"]) * 100

In [24]:
df

    Name  Obtain  Total_Marks  Percentage
0  Arham      80          100        80.0
1  Ameen      23          100        23.0
2  Ammar      32          100        32.0
3   Khan      60          100        60.0
4    Ali      26          100        26.0

In [ ]:
titanic_data